import { GetStaticProps, InferGetStaticPropsType, NextPage } from 'next';
import Head from 'next/head';
import { useEffect } from 'react';
import { Toaster } from 'react-hot-toast';

import Navbar from '../components/Navbar/Navbar';
import { useData } from '../context/DataContext';
import { User } from '../types';
import { getMe } from '../server/Api';

interface HomeProps extends InferGetStaticPropsType<typeof getStaticProps> {

}

const Home: NextPage<HomeProps> = ({myInfo}) => {
    const { setMyInfo } = useData();

    useEffect(() => {
        setMyInfo(myInfo);
    }, [myInfo, setMyInfo]);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    content="Generated by create next app"
                    name="description"
                />
                <meta
                    content="width=device-width, initial-scale=1"
                    name="viewport"
                />
                <link href="/favicon.ico" rel="icon" />
            </Head>
            <main className={'bg-brandGradient w-full h-screen flex justify-center'}>
                <Navbar />
            </main>
            <Toaster
                position='bottom-left'
                reverseOrder={true}
                toastOptions={{
                    style: {
                        width: '100%',
                        maxWidth: '532px',
                    },
                    success: {
                        style: {
                            background: '#F7FAFC',
                            color: '#7C899C',
                            border: '2px solid #29CC74',
                            borderRadius: '10px',
                        },
                    },
                    error: {
                        style: {
                            background: '#F7FAFC',
                            color: '#7C899C',
                            border: '2px solid #F56565',
                            borderRadius: '10px',
                        },
                    },
                }}
            />
        </>
    );
};

export default Home;

export const getStaticProps: GetStaticProps<{myInfo: User}> = async () => {
    const myInfo = await getMe();    

    return {
        props: {
            myInfo,
        },
    };
};