import { GetStaticProps, InferGetStaticPropsType, NextPage } from 'next';
import Head from 'next/head';
import { useEffect } from 'react';

import Navbar from '../components/Navbar/Navbar';
import { useData } from '../context/DataContext';
import { User } from '../types';

import { getMe } from './../server/User';

interface HomeProps extends InferGetStaticPropsType<typeof getStaticProps> {

}

const Home: NextPage<HomeProps> = ({myInfo}) => {
    const { setMyInfo } = useData();

    useEffect(() => {
        setMyInfo(myInfo);
    }, [myInfo, setMyInfo]);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    content="Generated by create next app"
                    name="description"
                />
                <meta
                    content="width=device-width, initial-scale=1"
                    name="viewport"
                />
                <link href="/favicon.ico" rel="icon" />
            </Head>
            <main className={'bg-brandGradient w-full h-screen flex justify-center'}>
                <Navbar />
            </main>

        </>
    );
};

export default Home;

export const getStaticProps: GetStaticProps<{myInfo: User}> = async () => {
    const myInfo = await getMe();    

    return {
        props: {
            myInfo,
        },
    };
};